USE WAREHOUSE COMPUTE_WH;

USE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE SCHEMA IF NOT EXISTS GOLD;

CREATE OR REPLACE TABLE GOLD.SALES_BY_STATE AS 
SELECT D.STATE,
SUM(F.SALES_PRICE) AS TOTAL_SALES
FROM SILVER.FACT_SALES F
JOIN SILVER.CUSTOMER_DIM D
ON F.CUSTOMER_SK = D.CUSTOMER_SK
GROUP BY D.STATE;

SELECT * FROM GOLD.SALES_BY_STATE LIMIT 100;

CREATE OR REPLACE TABLE GOLD.SALES_BY_YEAR AS 
SELECT YEAR(TRANSACTION_DATE) AS SALES_YEAR,
SUM(SALES_PRICE) AS TOTAL_SALES
FROM SILVER.FACT_SALES
GROUP BY SALES_YEAR;

SELECT * FROM GOLD.SALES_BY_YEAR;

CREATE OR REPLACE TABLE GOLD.MONTHLY_SALES AS 
SELECT 
DATE_TRUNC('MONTH', TRANSACTION_DATE) AS SALES_MONTH,
SUM(SALES_PRICE) AS TOTAL_SALES
FROM SILVER.FACT_SALES
GROUP BY SALES_MONTH;

SELECT * FROM GOLD.MONTHLY_SALES;

CREATE OR REPLACE TABLE GOLD.TOP_STORES AS 
SELECT
STORE_ID,
SUM(SALES_PRICE) AS TOTAL_SALES
FROM SILVER.FACT_SALES
GROUP BY STORE_ID
ORDER BY TOTAL_SALES DESC
LIMIT 10;

SELECT * FROM GOLD.TOP_STORES;

--PERFORMANCE VALIDATION

SELECT SUM(SALES_PRICE) FROM SILVER.FACT_SALES;
SELECT SUM(TOTAL_SALES) FROM GOLD.SALES_BY_STATE;


